### ISSUE TITLE
image with lower psnr , appearing visually good

### ISSUE THREAD

**Issue by nanmehta** [peteryuX/esrgan-tf2#2]

**Comment by nanmehta** [comment]
can u please tell me the reason, though esrgan has good results visually, but the psnr is low as compaired to psnr results

**Comment by peteryuX** [comment]
Hey, @nan-rock. Higher PSNR dose not mean better visual quality but fidelity.

**Comment by nanmehta** [comment]
okay .. and thanks for the code

**Comment by nanmehta** [comment]
hey,i need your help. when i am using imresize_np() to generte set 14 low resolution images, my images are getting distorted.
this is my code
`path="D:/SR_testing_datasets/Set14"
savepath="d:"
for img_name in os.listdir(path):
                raw_img = cv2.imread(os.path.join(path, img_name))
                shape=raw_img.shape
                #print(shape)
                new_image=imresize_np(raw_img, (2)).astype(np.uint8)
                #print("new",new_image.shape)
              
                #new_image=tf.image.resize( raw_img, [shape[0]+1,shape[1]+1], method ='bilinear'4
                result_img_path = os.path.join(savepath,img_name)
                #print(  result_img_path)
                #print(result_img_path)
                #print(os.listdir(result_img_path))
                a=cv2.imwrite(result_img_path, new_image)
                print(a)  `

![image](https://user-images.githubusercontent.com/67276550/87276306-ad362c00-c4fd-11ea-95b1-83acd6182564.png)

**Comment by peteryuX** [comment]
Try np.clip() value to 0 - 255 before astype to uint8

**Comment by nanmehta** [comment]
thanks a lot sir. 
wish u good luck.

**Comment by nanmehta** [comment]
hello sir, is the result evaluated on y channel or RGB

**Comment by weizhiliang0520** [comment]
Hi , i 'm very happy to see your codes.  but i'm very pool to coding.
when i run your code as  README, but i run   ./data/extract_subimages.py

the error as following:
`/home/cugxyy/anaconda3/envs/esrgan_tf2/bin/python3.6 /media/cugxyy/682d66c7-8836-4884-880a-361a16e098d1/LuoWei/esrgan2.0_luo/data/extract_subimages.py
Traceback (most recent call last):
  File "/media/cugxyy/682d66c7-8836-4884-880a-361a16e098d1/LuoWei/esrgan2.0_luo/data/extract_subimages.py", line 221, in <module>
    main()
  File "/media/cugxyy/682d66c7-8836-4884-880a-361a16e098d1/LuoWei/esrgan2.0_luo/data/extract_subimages.py", line 43, in main
    img_GT_list = _get_paths_from_images(GT_folder)
  File "/media/cugxyy/682d66c7-8836-4884-880a-361a16e098d1/LuoWei/esrgan2.0_luo/data/extract_subimages.py", line 207, in _get_paths_from_images
    assert osp.isdir(path), '{:s} is not a valid directory'.format(path)
AssertionError: ./data/DIV2K/DIV2K_train_HR is not a valid directory`

i don't know how to fill it. cu u tell how to do? thsanks!

**Comment by weizhiliang0520** [comment]
And all pre datas are prepared as README.  how strage it is!

**Comment by weizhiliang0520** [comment]
hello，i met a peoblem that i can't find the LR_path when run test. Only HR_path(Set5)  that downloaded from the url . Could you tell me truth?thanks!
